version: "3.8"
services:
  springApp:
    image: payara/server-full:5.2022.2-jdk11
    container_name: springApp
    volumes:
      - "./target/helloworld-0.0.1-SNAPSHOT.war:/opt/payara/deployments/helloworld-0.0.1-SNAPSHOT.war"
    ports:
      - "4848:4848"
      - "8080:8080"
      - "8181:8181"
